# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85b8973637779db10ba3311bd042a5b2"
name = "wishlist-inspire"
handle = "wishlist-inspire-243"
application_url = "https://dude-reading-reynolds-camera.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "haiders-dev-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://dude-reading-reynolds-camera.trycloudflare.com/auth/callback",
  "https://dude-reading-reynolds-camera.trycloudflare.com/auth/shopify/callback",
  "https://dude-reading-reynolds-camera.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
