# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef954fad351a34c158d4e38c5b876ecc"
name = "wishlist-inspire"
handle = "wishlist-inspire-359"
application_url = "https://localhost:56181"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aiverins.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://localhost:56181/auth/callback",
  "https://localhost:56181/auth/shopify/callback",
  "https://localhost:56181/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://webhooks/app/scopes_update"

[pos]
embedded = false
